# id|platform|default|description
fceumm|NES / Famicom|yes|FCEUmm
nestopia|NES / Famicom|yes|Nestopia UE
snes9x|SNES|yes|Snes9x
vice_x64|Commodore 64|yes|VICE x64
puae|Amiga|yes|PUAE
hatari|Atari ST|yes|Hatari
cap32|Amstrad CPC|yes|Caprice32
fuse|ZX Spectrum|yes|Fuse
bluemsx|MSX|yes|blueMSX
dosbox_svn|DOS|yes|DOSBox SVN
